### ISSUE TITLE
gem doesn't support pacticipants that have spaces in their names

### ISSUE THREAD

**Issue by mycargus** [pact-foundation/pact_broker-client#35] opened 2018-07-17 20:17 UTC
**Scenario 1 (failure)**
Given a pacticipant's name is "Pet Store" (one space)
And the pacticipant has published a Pact file to the Pact broker
When a person runs the following code snippet (see below)
Then pact-broker throws a "bad URI" error (full stack trace: https://gist.github.com/mycargus/e0d52b139d2bd74b2c50b9c2c11ced27)

`pact-broker create-version-tag -a "Pet Store" -b pact-broker.net -u pact -p broker -e 1 -t prod`

**Scenario 2 (failure)**
Given a pacticipant's name is "Pet Store" (one space)
And the pacticipant has published a Pact file to the Pact broker
When a person runs the following code snippet (see below)
Then the broker doesn't show a "prod" tag for the specified version
And the command didn't throw an error

`pact-broker create-version-tag -a "Pet%20Store" -b pact-broker.net -u pact -p broker -e 1 -t prod`

**Scenario 3 (success)**
Given a pacticipant's name is "PetStore" (no spaces)
And the pacticipant has published a Pact file to the Pact broker
When a person runs the following code snippet (see below)
Then the broker shows a "prod" tag for the specified version

`pact-broker create-version-tag -a "PetStore" -b pact-broker.net -u pact -p broker -e 1 -t prod`

pact_broker-client version 1.16.0
ruby version 2.4.2p198

**Comment by mycargus** [comment] 2018-07-17 20:18
I might be able to submit a PR for this later today

**Comment by mycargus** [comment] 2018-07-17 20:29
Turns out this bug only surfaces when I attempt to create a version tag against a pact broker that's running on my computer. It doesn't happen when I do the same against a pact broker running in a deployed environment. ¯\_(ツ)_/¯

**Comment by mycargus** [comment] 2018-07-17 21:29
I'm thinking this issue belongs to the pact broker project, not pact_broker-client

**Comment by bethesque** [comment] 2018-07-18 02:20
I cannot recreate it locally (the error is because I don't have anything running at pact-broker.docker)

```
$ pact-broker create-version-tag -a "Pet Store" -b pact-broker.docker -u pact -p broker -e 1 -t prod -v
Tagging Pet Store version 1 as prod
opening connection to pact-broker.docker:80...
Error making request - SocketError Failed to open TCP connection to pact-broker.docker:80 (getaddrinfo: nodename nor servname provided, or not known) /Users/bethanyskurrie/workspace/pact-foundation/pact_broker-client/lib/pact_broker/client/base_client.rb:96:in `put', attempt 1 of 3
```

I can recreate the bad URI problem (it's the space in the name that does it)

```
require 'uri'
URI("http://pact-broker.net/pacticipants/Quiz LTI/latest-version")
URI::InvalidURIError: bad URI(is not URI?): http://pact-broker.net/pacticipants/Quiz LTI/latest-version
```

```
URI("http://pact-broker.net/pacticipants/Quiz%20LTI/latest-version")
=> #<URI::HTTP http://pact-broker.net/pacticipants/Quiz%20LTI/latest-version>
```

This works. So, it should have nothing to do with whether it's a local or remote Pact Broker. You didn't by any chance upgrade the client library did you?

**Comment by bethesque** [comment] 2018-07-18 02:22
Did you deliberately not put in the "http://" at the start of the broker base url? I wonder if that affected it.

**Comment by bethesque** [comment] 2020-02-19 09:02
Closing until reproduced.

**Closed by bethesque** 2020-02-19 09:02 UTC
